<?php

namespace AppBundle\Entity;

/**
 * SpelerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpelerRepository extends \Doctrine\ORM\EntityRepository
{
}
